gsc_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from django.views.static import serve
from django.conf.urls import url


urlpatterns = [
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    path("controllroom/", admin.site.urls),
    path("", include("src.urls")),
    # path("staff/", include("staff.urls")),
    # path("admin/", admin.site.urls),
    # staticfiles & media files
    url(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    url(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]

admin.site.site_header = "BCPISKP Administration"

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path("", index, name="home"),
    path("login/", login, name="login"),
    path("logout/", logout_user, name="logout"),
    path("request-rest-password/", request_rest_password, name="request_rest_password"),
    path("intro/", introduction, name="intro"),
    path("purpose/", purpose, name="purpose"),
    path("president-speech/", president_speech, name="president_speech"),
    path("courtesy-speech/", courtesy_speech, name="courtesy_speech"),
    path("adviser/", adviser, name="adviser"),
    path("management/", management, name="management"),
    path("general/", general, name="general"),
    path("election/", election, name="election"),
    path("election/<int:pk>/", election_details, name="election_details"),
    path("vote/<int:election_id>/", vote, name="vote"),
    # member
    path("requirements/", requirements, name="requirements"),
    path("how-to-be-member/", how_to_be_member, name="how_to_be_member"),
    path("admission-form/", admission_form, name="admission_form"),
    path("member-list/", member_list, name="member_list"),
    path("member-detail/<int:pk>/", member_detail, name="member_detail"),
    path("general-member/", general_member, name="general_member"),
    path("lifetime-member/", lifetime_member, name="lifetime_member"),
    path("honorary-member/", founding_member, name="founding_member"),
    path("member-info/", member_info, name="member_info"),
    path("member-share/", member_share, name="member_share"),
    #  downloads
    path("policies/", policies, name="policies"),
    #
    path("collection-info/", collection_info, name="collection_info"),
    path("audit-report/", audit_report, name="audit_report"),
    path("blood-group-dob/", blood_group_dob, name="blood_group_dob"),
    path("financial/", financial, name="financial"),
    path("other-way/", other_way, name="other_way"),
    path("education-scholarship/", education_scholarship, name="education_scholarship"),
    path("treatment/", treatment, name="treatment"),
    path("training/", training, name="training"),
    # Union
    path("union/history/", history, name="union_history"),
    path("union/employees/", employees, name="union_employees"),
    path("union/at-a-glance/", at_a_glance, name="union_at_a_glance"),
    path("union/info/", union_info, name="union_info"),
    path("union/freedom-fighter/", freedom_fighter, name="union_freedom_fighter"),
    path("union/villages/", village, name="union_village"),
    path("union/head-of-institutes/", principal_list, name="union_principal_list"),
    path(
        "union/president-of-institutes/",
        institute_president_list,
        name="union_institute_president",
    ),
    path(
        "union/hospitals-and-community-centers/",
        hospital_commiunity_center,
        name="union_hospital_community_center",
    ),
    path("union/institutes/", institute, name="union_institutes"),
    path("union/mosques/", mosque, name="union_mosque"),
    # union/institute
    path("union/institute/sonatia/", sonatia, name="institute_sonatia"),
    # contact
    path("contact/", contact, name="contact"),
    # profile
    path("profile/", profile, name="profile"),
    path("profile/edit/", profile_edit, name="profile_edit"),
]

src/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import password_validation
from django.forms.models import inlineformset_factory

from .models import Candidate, Contact, Election, Member, PasswordResetRequest


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=False, label="ইমেইল (Optional)")
    password1 = forms.CharField(
        label="পাসওয়ার্ড",
        strip=False,
        widget=forms.PasswordInput,
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label="পাসওয়ার্ড নিশ্চিত",
        strip=False,
        widget=forms.PasswordInput,
    )

    class Meta:
        model = User
        fields = ["email", "password1", "password2"]
        labels = {"email": "ইমেইল"}


class PasswordResetForm(forms.ModelForm):
    new_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = PasswordResetRequest
        exclude = ["done"]


class UserEditForm(forms.ModelForm):
    email = forms.EmailField(required=False, label="ইমেইল (Optional)")

    class Meta:
        model = User
        fields = ["email"]
        labels = {"email": "ইমেইল"}


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ["name", "email", "phone", "subject", "message"]
        widgets = {
            "message": forms.Textarea(
                attrs={
                    "rows": "5",
                },
            ),
        }


MEMBER_TYPES = (
    ("g", "সাধারণ সদস্য"),
    ("l", "আজীবন সদস্য"),
    ("f", "প্রতিষ্ঠাতা সদস্য"),
)


class MemberForm(forms.ModelForm):
    member_type = forms.ChoiceField(label="সদস্যের ধরন", choices=MEMBER_TYPES)

    class Meta:
        model = Member
        exclude = [
            "user",
            "is_approved",
        ]
        labels = {
            "full_name": "নাম",
            "father_name": "বাবার নাম",
            "mother_name": "মায়ের নাম",
            "passport": "পাসপোর্ট",
            "date_of_birth": "জন্ম তারিখ",
            "phone": "মোবাইল/ফোন নং",
            "member_type": "সদস্যের ধরন",
            "village": "গ্রাম",
            "post_office": "পোস্ট অফিস",
            "upazilla": "উপজেলা",
            "zilla": "জেলা",
            "country": "দেশ (বর্তমান অবস্থানরত)",
            "image": "ছবি",
            "is_agreed": "অঙ্গীকারনামা",
        }

        widgets = {
            "date_of_birth": forms.DateInput(
                attrs={
                    "type": "date",
                },
            ),
        }


month_choice = (
    (1, "জানুয়ারী"),
    (2, "ফেব্রুয়ারী"),
    (3, "মার্চ"),
    (4, "এপ্রিল"),
    (5, "মে"),
    (6, "জুন"),
    (7, "জুলাই"),
    (8, "অগাস্ট"),
    (9, "সেপ্টেম্বর"),
    (10, "অক্টোবর"),
    (11, "নভেম্বর"),
    (12, "ডিসেম্বর"),
)


class QueryForm(forms.Form):
    month = forms.ChoiceField(
        label="Select a Month", choices=month_choice, widget=forms.Select
    )
    year = forms.IntegerField(min_value=2000, max_value=3000)


class LoginForm(forms.Form):
    passport = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "পাসপোর্ট"}), label=""
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "পাসওয়ার্ড"}), label=""
    )


class ElectionForm(forms.ModelForm):
    class Meta:
        model = Election
        fields = ["name"]


class CandidateForm(forms.ModelForm):
    class Meta:
        model = Candidate
        fields = "__all__"


CandidateFormFormSet = inlineformset_factory(
    Election, Candidate, form=CandidateForm, fields=["user"], extra=1, can_delete=True
)

templates/snippets/ad.html
{% load static %}
<div id="carouselExampleControls" class="carousel slide my-5" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'img/slide_one.jpeg' %}" class="d-block w-100" alt="..." height="150px">
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/slide_two.jpeg' %}" class="d-block w-100" alt="..." height="150px">
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/slide_three.jpeg' %}" class="d-block w-100" alt="..." height="150px">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

templates/snippets/footer.html
<footer class="bg-navy-blye pt-5">
	<div class="container-fluid pb-2">
		<div class="row">
			<div class="col-md-3">
				<h4 class="border-bottom pb-1 mb-3">Contact Details</h4>
				<h6 class="text-info">প্রধান কার্যালয়ঃ</h6>
				<address>
					চান্দলা <br>
					ব্রাহ্মণ পাড়া, কুমিল্লা।<br>
					<strong><i class="fa fa-envelope text-info mr-2"></i></strong> brihattarchandlaipskp@gmail.com <br>
					<strong><i class="fa fa-phone text-info mr-2"></i></strong> +৮৮ ০১৮৩৫১০২৬৭২
				</address>

			</div>
			<div class="col-md-3">
				<h4 class="border-bottom pb-1 mb-3">IMPORTANT LINK</h4>
				<ul class="list-group-flush">
					<li class="list-group-items">
						<i class="far fa-hand-point-right"></i>
						<a href="https://www.bdjobs.com/" class="text-light" target="_blank"
							rel="noopener noreferrer">www.bdjobs.com</a>
					</li>
					<li class="list-group-items">
						<i class="far fa-hand-point-right"></i>
						<a href="https://kormo.google.com/" class="text-light" target="_blank"
							rel="noopener noreferrer">kormo.google.com</a>
					</li>
					<li class="list-group-items">
						<i class="far fa-hand-point-right"></i>
						<a href="https://www.glassdoor.com/index.htm" class="text-light" target="_blank"
							rel="noopener noreferrer">www.glassdoor.com</a>
					</li>
				</ul>
			</div>
			<div class="col-md-2">
				<h4 class="border-bottom pb-1 mb-3">Registration</h4>
				<div class="mb-3">
					<a href="" class="text-white">
						<i class="far fa-hand-point-right mr-2"></i>
						সদস্য ফর্ম
					</a>
				</div>
				<h4 class="border-bottom pb-1 mt-4">Follow Us</h4>
				<div class="">
					<a class="text-white" href="https://www.facebook.com/bcpiskp" target="_blank">
						<i class="fab fa-facebook text-info"></i> Facebook
					</a>
					<br>
					<a class="text-white" href="https://www.youtube.com/channel/UCPnZLxNkb4Yh6YYg7xjCdKg"
						target="_blank">
						<i class="fab fa-youtube text-info"></i> Youtube
					</a>
				</div>
			</div>
			<div class="col-md-4">
				<h4 class="border-bottom pb-1 mb-3">BANK DETAILS</h4>
				<div class="mb-3">
					<div class="text-info"><strong>Name</strong></div>
					MD. NAZRUL ISLAM <br>
					MD. SULEMAN KABIR <br>
					MD. MOHAMMAD ABDUR RAHAMAN SARKER
					<div class=""><strong class="text-info">ACCOUNT NO: </strong> 9901182466685</div>
					<div class=""><strong class="text-info">BRANCE: </strong> CHANDLA/KUTI BAZAR</div>
					<div class=""><strong class="text-info">ROUTING NO: </strong> 015121095</div>
					<h5 class="text-info">AL- ARAFAH ISLAMI BANK LIMITED</h5>
					<div class=""><strong class="text-info">Nagad: </strong> +88 01311824169</div>
					<div class=""><strong class="text-info">Bkash: </strong> +88 01836017944 (Personal)</div>
				</div>
			</div>
		</div>
	</div>
	<div class="footer-bottom bg-dark-blue">
		<div class="container-fluid py-2">
			<div class="text-center">
				©{% now 'Y' %} Copyrights <a href="{% url 'home' %}" class="text-light"><strong>BCPISKP</strong></a> |
				All rights Reserved
			</div>
		</div>
	</div>
</footer>

templates/snippets/header.html
{% load static %}

<header>
	<!-- Top Menu  -->
	<div class="bg-blue">
		<div class="text-center d-flex flex-wrap justify-content-center py-1">
			<div class="mr-2">
				<i class="fas fa-phone text-info"></i>
				+8801835102672
			</div>
			<div class="mr-2">
				<i class="fab fa-whatsapp text-info"></i>
				+966571804996
			</div>
			<div class="mr-2">
				<a class="text-white" href="mailto:brihattarchandlaipskp@gmail.com">
					<i class="fas fa-envelope text-info"></i>
					brihattarchandlaipskp@gmail.com
				</a>
			</div>
			<div>
				<i class="fas fa-map-marker-alt text-info"></i>
				চান্দলা, ব্রাহ্মণ পাড়া, কুমিল্লা।
			</div>
		</div>
	</div>
	<!-- /Top Menu  -->

	<!-- Logo Menu  -->
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
				<div class="row logo-menu d-flex flex-column flex-md-row justify-content-md-between align-items-center">
					<!-- Logo Menu Left  -->
					<div class="logo-menu-left col-12 col-md-4">
						<!-- <img src="" alt="Logo"> -->
						<a href="{% url 'home' %}"><img class="img-fluid" style="cursor: pointer;" src="{% static 'img/update_logo.png' %}" alt="Logo"></a>
					</div>
					<!-- /Logo Menu Left  -->

					<!-- Logo Menu Right  -->
					<div class="logo-menu-right col-12 col-md-8">
						<div class="quran_ayat text-center text-md-right">
							<h5 class="ayat text-info">"
								তোমরা সবাই মিলে আল্লাহর রশি (কোরআন) -কে শক্ত করে আকড়েঁ ধরো এবং কখনো পরস্পর বিচ্ছিন্ন হয়ো
								নাহ।"
							</h5>
							<h6 class="source text-blue"><strong>- আল-কোরআন (০২ঃ১০৩)</strong></h6>
						</div>
					</div>
					<!-- Logo Menu Right  -->
				</div>
				<!-- Logo Menu  -->
			</div>
		</div>
	</div>
	<!-- Main Menu  -->
	<div class="main-menu">
		{% include "snippets/navbar.html" %}
	</div>
	<!-- /Main Menu  -->
</header>

templates/snippets/job_web_links.html
<div class="card border-0">
    <h5 class="card-header bg-blue">চাকরির ওয়েবলিংক</h5>
    <div class="card-body">
        <ul class="list-group-flush">
            <li class="list-group-items">
                <i class="far fa-hand-point-right"></i>
                <a href="https://www.bdjobs.com/" target="_blank" rel="noopener noreferrer">www.bdjobs.com</a>
            </li>
            <li class="list-group-items">
                <i class="far fa-hand-point-right"></i>
                <a href="https://kormo.google.com/" target="_blank" rel="noopener noreferrer">kormo.google.com</a>
            </li>
            <li class="list-group-items">
                <i class="far fa-hand-point-right"></i>
                <a href="https://www.glassdoor.com/index.htm" target="_blank"
                    rel="noopener noreferrer">www.glassdoor.com</a>
            </li>
        </ul>
    </div>
</div>

templates/snippets/mainmenu.html
<ul id="mainmenu" class="mainmenu d-lg-flex fle text-white">
    <li>
        <a href="{% url 'home' %}">হোম</a>
    </li>
    <li class="dropdown">
        <div class="d-flex justify-content-between">
            <a href="">আমাদের সম্পর্কে</a>
            <i class="fas fa-angle-right mt-1 d-lg-none angleRight"></i>
            <i class="fas fa-angle-down mt-1 d-none d-lg-none angleDown"></i>
        </div>
        <ul class="drop-menu">
            <li><a href="{% url 'intro' %}">পরিচিতি</a></li>
            <li><a href="{% url 'purpose' %}">লক্ষ্য ও উদ্দেশ্য</a></li>
            <li><a href="{% url 'president_speech' %}">সভাপতির বক্তব্য</a></li>
        </ul>
    </li>
    <li class="dropdown">
        <div class="d-flex justify-content-between">
            <a href="#">পরিষদ</a>
            <i class="fas fa-angle-right mt-1 d-lg-none angleRight"></i>
            <i class="fas fa-angle-down mt-1 d-none d-lg-none angleDown"></i>
        </div>
        <ul class="drop-menu">
            <li><a href="{% url 'adviser' %}">উপদেষ্টা পরিষদ</a>
            </li>
            <li><a href="{% url 'management' %}">কার্য্যনির্বাহী পরিষদ</a>
            </li>
            <li><a href="{% url 'general' %}">ওয়ার্ড কমিটি</a>
            </li>
            <li><a href="{% url 'election' %}">নির্বাচন কমিশন</a>
            </li>
        </ul>
    </li>
    <li class="dropdown">
        <div class="d-flex justify-content-between">
            <a href="#">সদস্য</a>
            <i class="fas fa-angle-right mt-1 d-lg-none angleRight"></i>
            <i class="fas fa-angle-down mt-1 d-none d-lg-none angleDown"></i>
        </div>
        <ul class="drop-menu">
            <li><a href="{% url 'requirements' %}">সদস্য হওয়ার যোগ্যতা</a>
            </li>
            <li><a href="{% url 'how_to_be_member' %}">কিভাবে সদস্য হবেন</a>
            </li>
            <li><a href="{% url 'admission_form' %}">সদস্য ভর্তি ফর্ম</a>
            </li>
            <li><a href="{% url 'admission_form' %}">প্রতিষ্টানা সদস্য</a>
            </li>
            <li><a href="{% url 'admission_form' %}">উপদেষ্টা সদস্য</a>
            </li>
            <li><a href="{% url 'general_member' %}">সাধারন সদস্য</a>
            </li>
            <li><a href="{% url 'lifetime_member' %}">আজীবন সদস্য</a>
            </li>
        </ul>
    </li>

    <li>
        <a href="#">অনুদান সংগ্রহ </a>
    </li>

    <li class="dropdown">
        <div class="d-flex justify-content-between">
            <a href="#">কল্যান </a>
            <i class="fas fa-angle-right mt-1 d-lg-none angleRight"></i>
            <i class="fas fa-angle-down mt-1 d-none d-lg-none angleDown"></i>
        </div>
        <ul class="drop-menu">
            <li>
                <a href="{% url 'scholarship' %}">কোরআন প্রশিক্ষণ</a>
            </li>
            <li>
                <a href="{% url 'treatment' %}">শিক্ষা বৃত্তি</a>
            </li>
            <li>
                <a href="{% url 'training' %}">কর্জে হাসানা</a>
            </li>
            <li>
                <a href="{% url 'training' %}">চিকিৎসা সহায়তা</a>
            </li>
            <li>
                <a href="{% url 'training' %}">দক্ষতা উন্নয়ন ও প্রশিক্ষণ</a>
            </li>
            <li>
                <a href="{% url 'training' %}">বেকারত্ব দূরীকরণ</a>
            </li>
            <li>
                <a href="{% url 'training' %}">বিবিধ</a>
            </li>
        </ul>
    </li>
    <li class="dropdown">
        <div class="d-flex justify-content-between">
            <a href="#">ডাউনলোড </a>
            <i class="fas fa-angle-right mt-1 d-lg-none angleRight"></i>
            <i class="fas fa-angle-down mt-1 d-none d-lg-none angleDown"></i>
        </div>
        <ul class="drop-menu">
            <li>
                <a href="#">গঠনতন্ত্র</a>
            </li>
            <li>
                <a href="#">সদস্য ভর্তি ফর্ম ডাউনলোড</a>
            </li>
            <li>
                <a href="#">সাময়িকী</a>
            </li>
            <li>
                <a href="#">কুইজ-স্কুল</a>
            </li>
            <li>
                <a href="#">কুইজ-মাদ্রাসা</a>
            </li>
        </ul>
    </li>

    <li>
        <a href="#">ফটোগ্যালারী</a>
    </li>
    <li>
        <a href="#">নিউজ ও ইভেন্টস্</a>
    </li>
    <li class="dropdown">
        <div class="d-flex justify-content-between">
            <a href="#">বৃহত্তর চান্দলা</a>
            <i class="fas fa-angle-right mt-1 d-lg-none angleRight"></i>
            <i class="fas fa-angle-down mt-1 d-none d-lg-none angleDown"></i>
        </div>
        <ul class="drop-menu">
            <li>
                <a href="{% url 'union_history' %}">এক নজরে বৃহত্তর চান্দলা</a>
            </li>
            <li>
                <a href="{% url 'union_employees' %}">মসজিদ তালিকা</a>
            </li>
            <li>
                <a href="{% url 'union_at_a_glance' %}">ওয়ার্ড ও গ্রাম</a>
            </li>
            <li>
                <a href="{% url 'union_info' %}">শিক্ষা প্রতিষ্ঠানসমূহ</a>
            </li>
            <li>
                <a href="{% url 'union_freedom_fighter' %}">স্মরণীয় ব্যক্তিত্ব</a>
            </li>
            <li>
                <a href="{% url 'union_village' %}">মুক্তিযোদ্ধা তালিকা</a>
            </li>
        </ul>
    </li>
    <li>
        <a href="{% url 'contact' %}">যোগাযোগ</a>
    </li>
    {% if request.user %}
    {% if request.user.groups.all %}
    <li class="dropdown">
        <div class="d-flex justify-content-between">
            <a href="{% url 'staff-index' %}">এডমিন</a>
            <i class="fas fa-angle-right mt-1 d-lg-none angleRight"></i>
            <i class="fas fa-angle-down mt-1 d-none d-lg-none angleDown"></i>
        </div>
        <ul class="wsmenu-submenu drop-menu">
            <li><a href="{% url 'logout' %}">লগ আউট</a>
            </li>
        </ul>
    </li>
    {% else %}
    <li>
        <a href="{% url 'logout' %}">সদস্য লগইন</a>
    </li>
    {% endif %}

    {% else %}
    <li>
        <a href="{% url 'login' %}">সদস্য লগইন</a>
    </li>
    {% endif %}
</ul>

templates/snippets/member_list.html
{% load static %}
<div class="table-responsive">
    <table class="table table-bordered">
        <thead class="bg-blue">
            <tr>
                <th>ছবি</th>
                <th>নাম</th>
                <th>জেলা</th>
                <th>দেশ</th>
                <th>মোবাইল নম্বর</th>
                {% if request.user.is_staff %}
                <th>এ্যাকশন</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for member in members %}
            <tr>
                <td>
                    <img class="img-thumbnail member-list-imge"
                        src="{% if member.image %} {{member.image.url}} {%else%} {% static 'img/default_member.png' %} {% endif %}"
                        alt="{{member.name}}">
                </td>
                <td>{{ member.full_name }}</td>
                <td>{{ member.zilla }}</td>
                <td>{{ member.country }}</td>
                <td>{{ member.phone }}</td>
                {% if request.user.is_staff %}
                <td>
                    <a class="btn btn-info btn-sm text-white" href="{% url 'member_detail' member.pk %}">
                        <i class="fa fa-eye"></i>
                    </a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

templates/snippets/member_login.html
{% load crispy_forms_tags %}

<div class="card border-0">
  <h5 class="login card-header bg-blue"> {% if request.user.is_authenticated %} স্বাগতম {% else %} সদস্যের লগইন
    {% endif %}
  </h5>

  <div class="card-body">
    {% if request.user.is_authenticated %}
    <p>স্বাগতম <strong>{{request.user.username}}</strong></p>

    {% else %}
    <form class='' action="{% url 'login' %}" method="POST">
      {% csrf_token %}

      <div id="div_id_passport" class="form-group">
        <input type="text" name="passport" placeholder="পাসপোর্ট" class="textinput textInput form-control" required=""
          id="id_passport">
      </div>
      <div id="div_id_password" class="form-group">
        <input type="password" name="password" placeholder="পাসওয়ার্ড" class="textinput textInput form-control"
          required="" id="id_password">
      </div>

      <button type="submit" class="btn blue-btn btn-block mt-3">লগইন <i class="fas fa-sign-in-alt"></i></button>
    </form>
    {% endif %}
  </div>
</div>

templates/snippets/messages.html
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible fade show my-2" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}

templates/snippets/notice_board.html
<div class="card border-0">
  <h5 class="card-header bg-blue">নোটিশ বোর্ড</h5>
  <div class="card-body p-0 accordion" id="accordionExample">
    {% for notice in notices %}
    <div class="card border-0">
      <div class="card-header p-1 bg-white" id="heading{{notice.id}}">
        <a href="" class="px-2 py-2 d-block" type="button" data-toggle="collapse" data-target="#collapse{{notice.id}}"
          aria-expanded="true" aria-controls="collapseOne">
          <i class="far fa-hand-point-right"></i> {{notice.title}}
        </a>
      </div>

      <div id="collapse{{notice.id}}" class="collapse {% if forloop.counter0 == 0 %} show {% endif %}"
        aria-labelledby="heading{{notice.id}}" data-parent="#accordionExample">
        <div class="card-body">
          {{notice.description}}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

templates/snippets/visitor_count.html
<!-- <h5 class="notice">Visitor Counter</h5>
<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Rerum cumque eveniet sit non
    tempore
    consectetur rem voluptatum atque veritatis sapiente earum voluptates magnam doloribus,
    at
    dolorem numquam. Tempora saepe a quam labore recusandae. Minus vero non, pariatur
    suscipit
    architecto molestiae sint quidem eum dolorum, esse quae illum praesentium dignissimos
    dolor!
</p> -->